### ISSUE TITLE
Google Assistant SDK not detecting END_OF_UTTERANCE

### ISSUE THREAD

**Issue by Nitya05** [googlesamples/assistant-sdk-cpp#13]
Hey,
What are the probable reasons for the SDK not detecting an END_OF_UTTERANCE for a request?
There have been a lot of instances, when the channel is created properly, but the sdk doesn't come up with a proper response (including end-of-utterance). Can it be because of some authentication failure that I am unable to track or is it something else?

**Comment by Nitya05** [comment]
No, I am using ALSA INPUT. 
I am getting 401 error at times. It's like the same refresh token works at some times, and it doesn't at some other times, giving a 401 error.

**Comment by Fleker** [comment]
We are aware of some issues with authenticating on the service.

Can you try running one of the audio samples to verify that `END_OF_UTTERANCE` is received. Issues may be due to authentication or due to the quality of the recorded audio sample.

**Comment by cogmeta** [comment]
Ok, it finally compiles (after getting rid of service_account_util.o which no longer exists :)).

I cant test it though since i dont have microphone on the device. Will test it tonight and update you. Thanks.

**Comment by hkwan72** [comment]
hello,
does SDK C++ support some event which can be used in python version as like ;EventType.ON_CONVERSATION_TURN_STARTED/EventType.ON_START_FINISHED/EventType.ON_RECOGNIZING_SPEECH_FINISHED/EventType.ON_CONVERSATION_TURN_FINISHED/EventType.ON_DEVICE_ACTION; ?
what i want is to detect a predefined special word or phrase by using google assistant SDK C++ version as like below;
"ok google", " music play / stop / pause/ next /previous", " set volume up/ down/high/medium/low" " bluetooth on/off" 
 in order to implement them as like the process_event(self, event) implemented in hotword.py of python version, i guess below several events provided in python version could be supported in C++ version,too.
if so, how can i use those event in C++ version?
is there something example code in C++ version ?
if possible, please let  me know some guide to implement them in C++ version.

thanks

**Comment by Fleker** [comment]
@hkwan72 you should look at adding [device actions](https://developers.google.com/assistant/sdk/device-actions-overview). While the C++ sample does not have the same `EventType` API, you can figure those out yourself as you able to control the request and do get back responses.
